# Generated by Django 5.1.5 on 2025-08-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rename_house_name_rentals_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.rentals'),
            preserve_default=False,
        ),
    ]
