# Generated by Django 4.2 on 2026-05-04 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0005_remove_rentals_location_remove_rentals_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=52)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='rentals',
            old_name='owner_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='rentals',
            old_name='owner_post_code',
            new_name='post_code',
        ),
        migrations.AddField(
            model_name='rentals',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rentals/'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='available_till',
            field=models.DateField(default=datetime.datetime(2027, 5, 4, 11, 58, 44, 793291, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.CreateModel(
            name='UnavailableDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='rentals.rentals')),
            ],
        ),
        migrations.AddField(
            model_name='rentals',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rentals.category'),
            preserve_default=False,
        ),
    ]
