# Generated by Django 4.2 on 2026-05-07 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_category_rename_name_location_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='available_till',
            field=models.DateField(default=datetime.datetime(2027, 5, 7, 12, 50, 2, 452993, tzinfo=datetime.timezone.utc)),
        ),
    ]
