# Generated by Django 4.2 on 2026-05-28 11:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_rentals_available_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentals',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentals',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='available_till',
            field=models.DateField(default=datetime.datetime(2027, 5, 28, 11, 45, 41, 167513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
