# Generated by Django 4.2 on 2026-06-04 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0008_rentals_active_rentals_date_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentals",
            name="available_till",
            field=models.DateField(
                default=datetime.datetime(
                    2027, 6, 4, 13, 9, 58, 113706, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="owner_number",
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
