# Generated by Django 4.2 on 2026-06-08 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0009_alter_rentals_available_till_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="rentals",
            name="available_till",
            field=models.DateField(
                default=datetime.datetime(
                    2027, 6, 8, 12, 30, 17, 633387, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="UnavailableDates",
        ),
        migrations.AddField(
            model_name="availabledates",
            name="rental",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_dates",
                to="rentals.rentals",
            ),
        ),
    ]
