# Generated by Django 4.2 on 2026-06-10 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0010_availabledates_alter_rentals_available_till_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentals",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("flat_rate", "Flat Rate"),
                ],
                default="daily",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="available_till",
            field=models.DateField(
                default=datetime.datetime(
                    2027, 6, 10, 10, 42, 2, 130102, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
