# Generated by Django 4.2 on 2026-06-10 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0011_rentals_pricing_type_alter_rentals_available_till"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentals",
            name="available_till",
            field=models.DateField(
                default=datetime.datetime(
                    2027, 6, 10, 12, 20, 9, 220039, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("over_Shabbos", "Over Shabbos"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("flat_rate", "Flat Rate"),
                ],
                default="daily",
                max_length=18,
            ),
        ),
    ]
