# Generated by Django 4.2 on 2026-06-10 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0012_alter_rentals_available_till_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentals",
            name="available_till",
            field=models.DateField(
                default=datetime.datetime(
                    2027, 6, 10, 21, 53, 0, 810830, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="title",
            field=models.CharField(max_length=45),
        ),
    ]
