# Generated by Django 4.2 on 2026-06-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0013_alter_rentals_available_till_alter_rentals_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentals",
            name="available_from",
        ),
        migrations.RemoveField(
            model_name="rentals",
            name="available_till",
        ),
        migrations.AddField(
            model_name="rentals",
            name="old_amenities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="amenities",
            field=models.CharField(
                blank=True,
                choices=[
                    ("near_shul", "Near Shuls"),
                    ("eruv", "Within Eruv"),
                    ("separate_ovens", "Two Ovens"),
                    ("shabbos_mode", "Shabbos Clock"),
                    ("hot_plate", "Hot Plate"),
                    ("blech", "Blech Available"),
                    ("shabbos_kettle", "Shabbos Kettle / Urn"),
                    ("shabbos_lights", "Shabbos Lamps"),
                    ("shabbos_timer", "Shabbos Timers"),
                    ("near_kosher_shops", "Near Kosher Shops"),
                    ("near_mikvah", "Near Mikvah"),
                    ("near_park", "Near Parks / Playgrounds"),
                    ("near_public_transport", "Near Public Transport"),
                    ("kids_beds", "Kids Beds / Cots"),
                    ("high_chair", "High Chair"),
                    ("baby_bath", "Baby Bath"),
                    ("large_dining_table", "Large Dining Table"),
                    ("sukkah_available", "Sukkah Available"),
                    ("sukkah_space", "Space for Sukkah"),
                    ("pesach_kitchen", "Pesach Kitchen"),
                    ("wifi", "WiFi"),
                    ("air_con", "Air Conditioning"),
                    ("garden", "Garden"),
                    ("private_garden", "Private Garden"),
                    ("parking", "Parking"),
                    ("off_street_parking", "Off-Street Parking"),
                    ("wheelchair_access", "Wheelchair Accessible"),
                    ("washing_machine", "Washing Machine"),
                    ("dryer", "Dryer"),
                    ("linen_provided", "Linen Provided"),
                    ("towels_provided", "Towels Provided"),
                    ("family_friendly", "Family Friendly"),
                    ("quiet_area", "Quiet Area"),
                    ("safe_neighbourhood", "Safe Neighbourhood"),
                    ("near_lake_beach", "Near Lake / Beach"),
                    ("near_attractions", "Near Local Attractions"),
                    ("work_desk", "Work Desk"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
