# Generated by Django 4.2 on 2026-07-09 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0015_alter_rentals_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentals",
            name="date_added",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
