# Generated by Django 4.2 on 2026-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0016_alter_rentals_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentals",
            name="listing_duration",
            field=models.IntegerField(default=1),
        ),
    ]
