# Generated by Django 4.2 on 2026-07-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0017_rentals_listing_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentals",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("two_nights", "Minimum 2 Nights"),
                    ("over_Shabbos", "Over Shabbos"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("flat_rate", "Flat Rate"),
                ],
                default="daily",
                max_length=18,
            ),
        ),
    ]
