# Generated by Django 4.2 on 2026-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='time_sent',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
